var restaurants = [
{"location":"SoHo","price":"$", "atmosphere":"Romantic", "name":"Electric Waffle"},
{"location":"SoHo","price":"$", "atmosphere":"Romantic", "name":"Scene Serene"},
{"location":"SoHo","price":"$", "atmosphere":"Romantic", "name":"Neau Whirled"},
{"location":"SoHo","price":"$", "atmosphere":"Trendy", "name":"Atomic Coffee"},
{"location":"SoHo","price":"$", "atmosphere":"Trendy", "name":"Rococo"},
{"location":"SoHo","price":"$", "atmosphere":"Trendy", "name":"Poetry Jail"},
{"location":"SoHo","price":"$", "atmosphere":"Classy", "name":"Exposa"},
{"location":"SoHo","price":"$", "atmosphere":"Classy", "name":"Coffee Time"},
{"location":"SoHo","price":"$", "atmosphere":"Classy", "name":"Left and Right Burger"},
{"location":"SoHo","price":"$", "atmosphere":"Cozy", "name":"Captain Fennel"},
{"location":"SoHo","price":"$", "atmosphere":"Cozy", "name":"Club Hell Yea"},
{"location":"SoHo","price":"$", "atmosphere":"Cozy", "name":"Bring it!"},
{"location":"SoHo","price":"$", "atmosphere":"Rooftop", "name":"Dizé"},
{"location":"SoHo","price":"$", "atmosphere":"Rooftop", "name":"Juliet's Balcony"},
{"location":"SoHo","price":"$", "atmosphere":"Rooftop", "name":"The Sanguine"},
{"location":"SoHo","price":"$", "atmosphere":"Brunching", "name":"Splice"},
{"location":"SoHo","price":"$", "atmosphere":"Brunching", "name":"Bella Figala"},
{"location":"SoHo","price":"$", "atmosphere":"Brunching", "name":"Gator Taters"},
{"location":"SoHo","price":"$$", "atmosphere":"Romantic", "name":"The In Road Cafe"},
{"location":"SoHo","price":"$$", "atmosphere":"Romantic", "name":"Glassando"},
{"location":"SoHo","price":"$$", "atmosphere":"Romantic", "name":"Flying Potato"},
{"location":"SoHo","price":"$$", "atmosphere":"Trendy", "name":"So So Toboso"},
{"location":"SoHo","price":"$$", "atmosphere":"Trendy", "name":"The Mouth Piece"},
{"location":"SoHo","price":"$$", "atmosphere":"Trendy", "name":"Chorus"},
{"location":"SoHo","price":"$$", "atmosphere":"Classy", "name":"Local Motive"},
{"location":"SoHo","price":"$$", "atmosphere":"Classy", "name":"Neuroma"},
{"location":"SoHo","price":"$$", "atmosphere":"Classy", "name":"Nosh on the Net"},
{"location":"SoHo","price":"$$", "atmosphere":"Cozy", "name":"Figure Lean"},
{"location":"SoHo","price":"$$", "atmosphere":"Cozy", "name":"Dot Compadre"},
{"location":"SoHo","price":"$$", "atmosphere":"Cozy", "name":"Oy Vegas"},
{"location":"SoHo","price":"$$", "atmosphere":"Rooftop", "name":"JellyBone"},
{"location":"SoHo","price":"$$", "atmosphere":"Rooftop", "name":"Chocolate Mussolini"},
{"location":"SoHo","price":"$$", "atmosphere":"Rooftop", "name":"Olive Me"},
{"location":"SoHo","price":"$$", "atmosphere":"Brunching", "name":"Orb"},
{"location":"SoHo","price":"$$", "atmosphere":"Brunching", "name":"Misty August Morning"},
{"location":"SoHo","price":"$$", "atmosphere":"Brunching", "name":"Prawnbroker"},
{"location":"SoHo","price":"$$$", "atmosphere":"Romantic", "name":"Silver of Mine"},
{"location":"SoHo","price":"$$$", "atmosphere":"Romantic", "name":"Vitamin Seed"},
{"location":"SoHo","price":"$$$", "atmosphere":"Romantic", "name":"Coffee Universe"},
{"location":"SoHo","price":"$$$", "atmosphere":"Trendy", "name":"Goin' to the Roadhouse"},
{"location":"SoHo","price":"$$$", "atmosphere":"Trendy", "name":"Maguey"},
{"location":"SoHo","price":"$$$", "atmosphere":"Trendy", "name":"Fishstomp"},
{"location":"SoHo","price":"$$$", "atmosphere":"Classy", "name":"FoodBug"},
{"location":"SoHo","price":"$$$", "atmosphere":"Classy", "name":"Coffee Patch"},
{"location":"SoHo","price":"$$$", "atmosphere":"Classy", "name":"Mother Cabrini"},
{"location":"SoHo","price":"$$$", "atmosphere":"Cozy", "name":"The Crawfish Cantina"},
{"location":"SoHo","price":"$$$", "atmosphere":"Cozy", "name":"The Latvian Cat"},
{"location":"SoHo","price":"$$$", "atmosphere":"Cozy", "name":"The Blue Pig"},
{"location":"SoHo","price":"$$$", "atmosphere":"Rooftop", "name":"Kimono Open"},
{"location":"SoHo","price":"$$$", "atmosphere":"Rooftop", "name":"Brunchilli"},
{"location":"SoHo","price":"$$$", "atmosphere":"Rooftop", "name":"The Stool Pigeon"},
{"location":"SoHo","price":"$$$", "atmosphere":"Brunching", "name":"Parabolic Chicken"},
{"location":"SoHo","price":"$$$", "atmosphere":"Brunching", "name":"Lounge Potato"},
{"location":"SoHo","price":"$$$", "atmosphere":"Brunching", "name":"Enrondezvous"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Romantic", "name":"Hot Potty"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Romantic", "name":"Southern Soy"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Romantic", "name":"Rebuy Steak"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Trendy", "name":"Emptia"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Trendy", "name":"Nuxa"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Trendy", "name":"Savoree"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Classy", "name":"Buddha Bread"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Classy", "name":"C-Theory"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Classy", "name":"Exhibit E"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Cozy", "name":"Flypaper"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Cozy", "name":"Dutch Oven Gretel"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Cozy", "name":"The Jambalaya Joint"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Rooftop", "name":"Sugarpine"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Rooftop", "name":"Shoots and Spears"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Rooftop", "name":"The Coffee Funnel"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Brunching", "name":"Tivondra"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Brunching", "name":"Jen &amp; Barry's"},
{"location":"SoHo","price":"$$$$", "atmosphere":"Brunching", "name":"The Mardi Gras Menu"},
{"location":"Lower East Side","price":"$", "atmosphere":"Romantic", "name":"Prosperity Cafe"},
{"location":"Lower East Side","price":"$", "atmosphere":"Romantic", "name":"Tucson's Cantina"},
{"location":"Lower East Side","price":"$", "atmosphere":"Romantic", "name":"La Bonne Terre"},
{"location":"Lower East Side","price":"$", "atmosphere":"Trendy", "name":"BoozeBelly"},
{"location":"Lower East Side","price":"$", "atmosphere":"Trendy", "name":"Easy Speak"},
{"location":"Lower East Side","price":"$", "atmosphere":"Trendy", "name":"Froggy Bottom"},
{"location":"Lower East Side","price":"$", "atmosphere":"Classy", "name":"Sausage"},
{"location":"Lower East Side","price":"$", "atmosphere":"Classy", "name":"Subterfuse"},
{"location":"Lower East Side","price":"$", "atmosphere":"Classy", "name":"Kitchen Caboodle"},
{"location":"Lower East Side","price":"$", "atmosphere":"Cozy", "name":"Varqua"},
{"location":"Lower East Side","price":"$", "atmosphere":"Cozy", "name":"South Mouth"},
{"location":"Lower East Side","price":"$", "atmosphere":"Cozy", "name":"Mazaltov Cocktail"},
{"location":"Lower East Side","price":"$", "atmosphere":"Rooftop", "name":"Trademark Cafe"},
{"location":"Lower East Side","price":"$", "atmosphere":"Rooftop", "name":"The Prawn and Pig"},
{"location":"Lower East Side","price":"$", "atmosphere":"Rooftop", "name":"Sushi Logic"},
{"location":"Lower East Side","price":"$", "atmosphere":"Brunching", "name":"Crux Tux"},
{"location":"Lower East Side","price":"$", "atmosphere":"Brunching", "name":"Muscle Bar"},
{"location":"Lower East Side","price":"$", "atmosphere":"Brunching", "name":"Waugh Waugh Waugh"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Romantic", "name":"The Nine"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Romantic", "name":"Lunchpod"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Romantic", "name":"Zamora"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Trendy", "name":"eee Cummings"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Trendy", "name":"Vortex Mex"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Trendy", "name":"Elemantra"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Classy", "name":"Dear Meat"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Classy", "name":"The Defense Department"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Classy", "name":"Fish, Fat and the Otter"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Cozy", "name":"PreSlicely"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Cozy", "name":"Alluvia"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Cozy", "name":"Genome"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Rooftop", "name":"Coney Island Minibars"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Rooftop", "name":"Dandelar's"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Rooftop", "name":"Sponge"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Brunching", "name":"Steak Out"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Brunching", "name":"Spontaneous Combustion"},
{"location":"Lower East Side","price":"$$", "atmosphere":"Brunching", "name":"the Rig"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Romantic", "name":"Beluga Bandit"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Romantic", "name":"Coffee Planet"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Romantic", "name":"Get Ya Green Leafies"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Trendy", "name":"The Dapper Mongoose"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Trendy", "name":"Stone's Throw"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Trendy", "name":"Fiddler's Fig"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Classy", "name":"On High"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Classy", "name":"Feral"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Classy", "name":"The Mocha"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Cozy", "name":"Lambastica"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Cozy", "name":"Burger Glory"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Cozy", "name":"Glossy Trotsky"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Rooftop", "name":"Pantry Planet"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Rooftop", "name":"Corn-Fed Beef Bowl"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Rooftop", "name":"A Day Latte"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Brunching", "name":"Humvegain't"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Brunching", "name":"Prawntastic"},
{"location":"Lower East Side","price":"$$$", "atmosphere":"Brunching", "name":"Wasabi Good"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Romantic", "name":"Topeeka Bound"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Romantic", "name":"Bamboolong"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Romantic", "name":"Before Coffee"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Trendy", "name":"Pol Pot Pizza"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Trendy", "name":"Hell's BBQ"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Trendy", "name":"House of Chedder"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Classy", "name":"Montauk Mantra"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Classy", "name":"Arotiaka"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Classy", "name":"The West Blank"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Cozy", "name":"Belle' Pepper"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Cozy", "name":"Turnpike"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Cozy", "name":"Paella Machine"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Rooftop", "name":"Taco Bail"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Rooftop", "name":"Fresh Flesh"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Rooftop", "name":"Double Jump"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Brunching", "name":"ExoPlanet"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Brunching", "name":"Ignia"},
{"location":"Lower East Side","price":"$$$$", "atmosphere":"Brunching", "name":"Tandoori Vittles"},
{"location":"China Town","price":"$", "atmosphere":"Romantic", "name":"Echo Shack"},
{"location":"China Town","price":"$", "atmosphere":"Romantic", "name":"Mardi Grub"},
{"location":"China Town","price":"$", "atmosphere":"Romantic", "name":"Bacon Dump"},
{"location":"China Town","price":"$", "atmosphere":"Trendy", "name":"Highway Ribbery"},
{"location":"China Town","price":"$", "atmosphere":"Trendy", "name":"Pilz"},
{"location":"China Town","price":"$", "atmosphere":"Trendy", "name":"Guru"},
{"location":"China Town","price":"$", "atmosphere":"Classy", "name":"Psycho Kitty"},
{"location":"China Town","price":"$", "atmosphere":"Classy", "name":"Zulu"},
{"location":"China Town","price":"$", "atmosphere":"Classy", "name":"Max Five"},
{"location":"China Town","price":"$", "atmosphere":"Cozy", "name":"Yearlove"},
{"location":"China Town","price":"$", "atmosphere":"Cozy", "name":"Mr. Beans"},
{"location":"China Town","price":"$", "atmosphere":"Cozy", "name":"Flame Thrower's Grill"},
{"location":"China Town","price":"$", "atmosphere":"Rooftop", "name":"Peril"},
{"location":"China Town","price":"$", "atmosphere":"Rooftop", "name":"Bob Mutton"},
{"location":"China Town","price":"$", "atmosphere":"Rooftop", "name":"Strip Drag"},
{"location":"China Town","price":"$", "atmosphere":"Brunching", "name":"The Beef Plank"},
{"location":"China Town","price":"$", "atmosphere":"Brunching", "name":"Guru Cricket"},
{"location":"China Town","price":"$", "atmosphere":"Brunching", "name":"Floq"},
{"location":"China Town","price":"$$", "atmosphere":"Romantic", "name":"Fort Angus"},
{"location":"China Town","price":"$$", "atmosphere":"Romantic", "name":"Whip and Throttle"},
{"location":"China Town","price":"$$", "atmosphere":"Romantic", "name":"Save the Date"},
{"location":"China Town","price":"$$", "atmosphere":"Trendy", "name":"Bluez"},
{"location":"China Town","price":"$$", "atmosphere":"Trendy", "name":"Potata Pathos"},
{"location":"China Town","price":"$$", "atmosphere":"Trendy", "name":"Coffeeplosion"},
{"location":"China Town","price":"$$", "atmosphere":"Classy", "name":"Gage and Desoto"},
{"location":"China Town","price":"$$", "atmosphere":"Classy", "name":"Thought For Food"},
{"location":"China Town","price":"$$", "atmosphere":"Classy", "name":"Le Petit Chef"},
{"location":"China Town","price":"$$", "atmosphere":"Cozy", "name":"Tongue in Chic"},
{"location":"China Town","price":"$$", "atmosphere":"Cozy", "name":"Varmetta"},
{"location":"China Town","price":"$$", "atmosphere":"Cozy", "name":"Neitsche Bagel"},
{"location":"China Town","price":"$$", "atmosphere":"Rooftop", "name":"Caffeine Conscious"},
{"location":"China Town","price":"$$", "atmosphere":"Rooftop", "name":"Candy Ask"},
{"location":"China Town","price":"$$", "atmosphere":"Rooftop", "name":"Frelika"},
{"location":"China Town","price":"$$", "atmosphere":"Brunching", "name":"The Backyard Chef"},
{"location":"China Town","price":"$$", "atmosphere":"Brunching", "name":"Constant Cafe"},
{"location":"China Town","price":"$$", "atmosphere":"Brunching", "name":"Tostada Oblongata"},
{"location":"China Town","price":"$$$", "atmosphere":"Romantic", "name":"Of Mice and Mein"},
{"location":"China Town","price":"$$$", "atmosphere":"Romantic", "name":"Here's the Beef"},
{"location":"China Town","price":"$$$", "atmosphere":"Romantic", "name":"Torpor Ritz"},
{"location":"China Town","price":"$$$", "atmosphere":"Trendy", "name":"Cowtown"},
{"location":"China Town","price":"$$$", "atmosphere":"Trendy", "name":"Or Chard"},
{"location":"China Town","price":"$$$", "atmosphere":"Trendy", "name":"The Featured Artichoke"},
{"location":"China Town","price":"$$$", "atmosphere":"Classy", "name":"The Velvet Snail"},
{"location":"China Town","price":"$$$", "atmosphere":"Classy", "name":"Scrap Opera"},
{"location":"China Town","price":"$$$", "atmosphere":"Classy", "name":"Doc Hollandaise"},
{"location":"China Town","price":"$$$", "atmosphere":"Cozy", "name":"Dreamia"},
{"location":"China Town","price":"$$$", "atmosphere":"Cozy", "name":"Zilla Place"},
{"location":"China Town","price":"$$$", "atmosphere":"Cozy", "name":"Lord Martini"},
{"location":"China Town","price":"$$$", "atmosphere":"Rooftop", "name":"Kettlepop"},
{"location":"China Town","price":"$$$", "atmosphere":"Rooftop", "name":"Qimonk"},
{"location":"China Town","price":"$$$", "atmosphere":"Rooftop", "name":"Cafe Happenstance"},
{"location":"China Town","price":"$$$", "atmosphere":"Brunching", "name":"Latté Prey"},
{"location":"China Town","price":"$$$", "atmosphere":"Brunching", "name":"Beef Storm"},
{"location":"China Town","price":"$$$", "atmosphere":"Brunching", "name":"Mini Bar"},
{"location":"China Town","price":"$$$$", "atmosphere":"Romantic", "name":"UpsZcale"},
{"location":"China Town","price":"$$$$", "atmosphere":"Romantic", "name":"Jackie Diamonds"},
{"location":"China Town","price":"$$$$", "atmosphere":"Romantic", "name":"Fruit Not Fries!"},
{"location":"China Town","price":"$$$$", "atmosphere":"Trendy", "name":"Spoonbeam"},
{"location":"China Town","price":"$$$$", "atmosphere":"Trendy", "name":"Orchestrata"},
{"location":"China Town","price":"$$$$", "atmosphere":"Trendy", "name":"Prawn Tong"},
{"location":"China Town","price":"$$$$", "atmosphere":"Classy", "name":"Exospace"},
{"location":"China Town","price":"$$$$", "atmosphere":"Classy", "name":"Coffee Corral"},
{"location":"China Town","price":"$$$$", "atmosphere":"Classy", "name":"The Salty Pigeon"},
{"location":"China Town","price":"$$$$", "atmosphere":"Cozy", "name":"Purb"},
{"location":"China Town","price":"$$$$", "atmosphere":"Cozy", "name":"The Handle Bar"},
{"location":"China Town","price":"$$$$", "atmosphere":"Cozy", "name":"Cut Fastball"},
{"location":"China Town","price":"$$$$", "atmosphere":"Rooftop", "name":"Station House"},
{"location":"China Town","price":"$$$$", "atmosphere":"Rooftop", "name":"Neitsche Forest"},
{"location":"China Town","price":"$$$$", "atmosphere":"Rooftop", "name":"The Hole in One"},
{"location":"China Town","price":"$$$$", "atmosphere":"Brunching", "name":"Curly Fries"},
{"location":"China Town","price":"$$$$", "atmosphere":"Brunching", "name":"Soup Opera"},
{"location":"China Town","price":"$$$$", "atmosphere":"Brunching", "name":"Cool Tofu"},
{"location":"TribeCa","price":"$", "atmosphere":"Romantic", "name":"Veggie Frown"},
{"location":"TribeCa","price":"$", "atmosphere":"Romantic", "name":"Ahui"},
{"location":"TribeCa","price":"$", "atmosphere":"Romantic", "name":"Broadway Wellborne"},
{"location":"TribeCa","price":"$", "atmosphere":"Trendy", "name":"Bee Salt"},
{"location":"TribeCa","price":"$", "atmosphere":"Trendy", "name":"Bravo"},
{"location":"TribeCa","price":"$", "atmosphere":"Trendy", "name":"Gray Bar"},
{"location":"TribeCa","price":"$", "atmosphere":"Classy", "name":"Darvane"},
{"location":"TribeCa","price":"$", "atmosphere":"Classy", "name":"Slow Kitchen"},
{"location":"TribeCa","price":"$", "atmosphere":"Classy", "name":"Dijon Bomb"},
{"location":"TribeCa","price":"$", "atmosphere":"Cozy", "name":"Nerd"},
{"location":"TribeCa","price":"$", "atmosphere":"Cozy", "name":"Housedown"},
{"location":"TribeCa","price":"$", "atmosphere":"Cozy", "name":"Prawnscape"},
{"location":"TribeCa","price":"$", "atmosphere":"Rooftop", "name":"Prism"},
{"location":"TribeCa","price":"$", "atmosphere":"Rooftop", "name":"Zenka"},
{"location":"TribeCa","price":"$", "atmosphere":"Rooftop", "name":"Tango Bango"},
{"location":"TribeCa","price":"$", "atmosphere":"Brunching", "name":"Coffee Matrix"},
{"location":"TribeCa","price":"$", "atmosphere":"Brunching", "name":"Vilnius"},
{"location":"TribeCa","price":"$", "atmosphere":"Brunching", "name":"Kitty McQueen"},
{"location":"TribeCa","price":"$$", "atmosphere":"Romantic", "name":"The Oz"},
{"location":"TribeCa","price":"$$", "atmosphere":"Romantic", "name":"Pickin' &amp; Lickin' Chicken"},
{"location":"TribeCa","price":"$$", "atmosphere":"Romantic", "name":"North Quark"},
{"location":"TribeCa","price":"$$", "atmosphere":"Trendy", "name":"Jute Box"},
{"location":"TribeCa","price":"$$", "atmosphere":"Trendy", "name":"Talendula"},
{"location":"TribeCa","price":"$$", "atmosphere":"Trendy", "name":"The Blackened Gridle"},
{"location":"TribeCa","price":"$$", "atmosphere":"Classy", "name":"Coffee Tsunami"},
{"location":"TribeCa","price":"$$", "atmosphere":"Classy", "name":"Encino"},
{"location":"TribeCa","price":"$$", "atmosphere":"Classy", "name":"Rubber Slapjack"},
{"location":"TribeCa","price":"$$", "atmosphere":"Cozy", "name":"Idetica"},
{"location":"TribeCa","price":"$$", "atmosphere":"Cozy", "name":"Gnu Grounds"},
{"location":"TribeCa","price":"$$", "atmosphere":"Cozy", "name":"SeaSky"},
{"location":"TribeCa","price":"$$", "atmosphere":"Rooftop", "name":"Terrapod"},
{"location":"TribeCa","price":"$$", "atmosphere":"Rooftop", "name":"Plonk"},
{"location":"TribeCa","price":"$$", "atmosphere":"Rooftop", "name":"The Robillet Roadhouse"},
{"location":"TribeCa","price":"$$", "atmosphere":"Brunching", "name":"Chevre"},
{"location":"TribeCa","price":"$$", "atmosphere":"Brunching", "name":"Could Be Worse"},
{"location":"TribeCa","price":"$$", "atmosphere":"Brunching", "name":"Felice"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Romantic", "name":"Beluga Banjo"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Romantic", "name":"Seafood Seranade"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Romantic", "name":"Pesto Quest"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Trendy", "name":"Pigzart"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Trendy", "name":"Dote"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Trendy", "name":"The Pope's Nose"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Classy", "name":"In That Vein"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Classy", "name":"Salsa Closet"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Classy", "name":"The Bid and Ask"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Cozy", "name":"Pre-fab Burritos"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Cozy", "name":"Liquid Ambassador"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Cozy", "name":"Chateau Low-blow"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Rooftop", "name":"PowerPrawn"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Rooftop", "name":"Valpreal"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Rooftop", "name":"Beer Bunker"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Brunching", "name":"The Swine Flew"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Brunching", "name":"Gogol"},
{"location":"TribeCa","price":"$$$", "atmosphere":"Brunching", "name":"Little Dostoevsky"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Romantic", "name":"Bowl and Bladder"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Romantic", "name":"Bella's"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Romantic", "name":"FlotSam's Club"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Trendy", "name":"Guru Smile"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Trendy", "name":"Ivridse"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Trendy", "name":"Pheromonia"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Classy", "name":"Tokyo Yo"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Classy", "name":"Floss and Joes"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Classy", "name":"Carnal Sanders"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Cozy", "name":"Moose Toe"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Cozy", "name":"Anocha"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Cozy", "name":"Aquoavo"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Rooftop", "name":"Space Pizza Initiative"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Rooftop", "name":"Cafe Response"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Rooftop", "name":"The Jolt"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Brunching", "name":"1000 BC (Before Coffee)"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Brunching", "name":"Pepperboard"},
{"location":"TribeCa","price":"$$$$", "atmosphere":"Brunching", "name":"The Salsa Project"},
{"location":"West Village","price":"$", "atmosphere":"Romantic", "name":"Satiance"},
{"location":"West Village","price":"$", "atmosphere":"Romantic", "name":"Hi Que"},
{"location":"West Village","price":"$", "atmosphere":"Romantic", "name":"Gorganic"},
{"location":"West Village","price":"$", "atmosphere":"Trendy", "name":"Mississippi Burnin' B.B.Q"},
{"location":"West Village","price":"$", "atmosphere":"Trendy", "name":"Organic Cannibal"},
{"location":"West Village","price":"$", "atmosphere":"Trendy", "name":"Mantis"},
{"location":"West Village","price":"$", "atmosphere":"Classy", "name":"Crabernacle"},
{"location":"West Village","price":"$", "atmosphere":"Classy", "name":"Ball Lightning"},
{"location":"West Village","price":"$", "atmosphere":"Classy", "name":"Karma Lhoke"},
{"location":"West Village","price":"$", "atmosphere":"Cozy", "name":"Pick and Shovel"},
{"location":"West Village","price":"$", "atmosphere":"Cozy", "name":"Thai Cheetos"},
{"location":"West Village","price":"$", "atmosphere":"Cozy", "name":"Tone Taco"},
{"location":"West Village","price":"$", "atmosphere":"Rooftop", "name":"Bob Cratchett"},
{"location":"West Village","price":"$", "atmosphere":"Rooftop", "name":"Food Frolic"},
{"location":"West Village","price":"$", "atmosphere":"Rooftop", "name":"Dandelion Greens"},
{"location":"West Village","price":"$", "atmosphere":"Brunching", "name":"Osmosis"},
{"location":"West Village","price":"$", "atmosphere":"Brunching", "name":"Atomic Donut"},
{"location":"West Village","price":"$", "atmosphere":"Brunching", "name":"Fish Matrix"},
{"location":"West Village","price":"$$", "atmosphere":"Romantic", "name":"Tuva"},
{"location":"West Village","price":"$$", "atmosphere":"Romantic", "name":"Round the World Coffee"},
{"location":"West Village","price":"$$", "atmosphere":"Romantic", "name":"Cabooze"},
{"location":"West Village","price":"$$", "atmosphere":"Trendy", "name":"Voodulce"},
{"location":"West Village","price":"$$", "atmosphere":"Trendy", "name":"Viune"},
{"location":"West Village","price":"$$", "atmosphere":"Trendy", "name":"Gnome Clone"},
{"location":"West Village","price":"$$", "atmosphere":"Classy", "name":"Sushi Spam"},
{"location":"West Village","price":"$$", "atmosphere":"Classy", "name":"In Ovation"},
{"location":"West Village","price":"$$", "atmosphere":"Classy", "name":"Zen BBQ"},
{"location":"West Village","price":"$$", "atmosphere":"Cozy", "name":"Share Reef"},
{"location":"West Village","price":"$$", "atmosphere":"Cozy", "name":"Umbria"},
{"location":"West Village","price":"$$", "atmosphere":"Cozy", "name":"Bid and Ask"},
{"location":"West Village","price":"$$", "atmosphere":"Rooftop", "name":"Fo Lita"},
{"location":"West Village","price":"$$", "atmosphere":"Rooftop", "name":"Magma"},
{"location":"West Village","price":"$$", "atmosphere":"Rooftop", "name":"Coffee Galaxy"},
{"location":"West Village","price":"$$", "atmosphere":"Brunching", "name":"Prawn Logic"},
{"location":"West Village","price":"$$", "atmosphere":"Brunching", "name":"Mocha Loco"},
{"location":"West Village","price":"$$", "atmosphere":"Brunching", "name":"Baba Rum"},
{"location":"West Village","price":"$$$", "atmosphere":"Romantic", "name":"Food Storm"},
{"location":"West Village","price":"$$$", "atmosphere":"Romantic", "name":"Razz Barney"},
{"location":"West Village","price":"$$$", "atmosphere":"Romantic", "name":"Cafe Visual"},
{"location":"West Village","price":"$$$", "atmosphere":"Trendy", "name":"Loopy Tuna"},
{"location":"West Village","price":"$$$", "atmosphere":"Trendy", "name":"Railroadies"},
{"location":"West Village","price":"$$$", "atmosphere":"Trendy", "name":"The Prawns Age"},
{"location":"West Village","price":"$$$", "atmosphere":"Classy", "name":"The Easy Seed"},
{"location":"West Village","price":"$$$", "atmosphere":"Classy", "name":"Eat Underground"},
{"location":"West Village","price":"$$$", "atmosphere":"Classy", "name":"Tiblisi"},
{"location":"West Village","price":"$$$", "atmosphere":"Cozy", "name":"Blue Ball"},
{"location":"West Village","price":"$$$", "atmosphere":"Cozy", "name":"Hash Browns and New Grounds"},
{"location":"West Village","price":"$$$", "atmosphere":"Cozy", "name":"Silkia"},
{"location":"West Village","price":"$$$", "atmosphere":"Rooftop", "name":"Nob Hill"},
{"location":"West Village","price":"$$$", "atmosphere":"Rooftop", "name":"Dogtown"},
{"location":"West Village","price":"$$$", "atmosphere":"Rooftop", "name":"The Flightless Bird"},
{"location":"West Village","price":"$$$", "atmosphere":"Brunching", "name":"Eros"},
{"location":"West Village","price":"$$$", "atmosphere":"Brunching", "name":"Retro Plum"},
{"location":"West Village","price":"$$$", "atmosphere":"Brunching", "name":"Parvenu Porkchop"},
{"location":"West Village","price":"$$$$", "atmosphere":"Romantic", "name":"Star Sixty Nine"},
{"location":"West Village","price":"$$$$", "atmosphere":"Romantic", "name":"UberPrawn"},
{"location":"West Village","price":"$$$$", "atmosphere":"Romantic", "name":"Work Flirt"},
{"location":"West Village","price":"$$$$", "atmosphere":"Trendy", "name":"Pheast West"},
{"location":"West Village","price":"$$$$", "atmosphere":"Trendy", "name":"Matre Deviant"},
{"location":"West Village","price":"$$$$", "atmosphere":"Trendy", "name":"Steak And Eddy's"},
{"location":"West Village","price":"$$$$", "atmosphere":"Classy", "name":"Lardé"},
{"location":"West Village","price":"$$$$", "atmosphere":"Classy", "name":"Bovine Oligarchy"},
{"location":"West Village","price":"$$$$", "atmosphere":"Classy", "name":"Big Bottom Beefworks"},
{"location":"West Village","price":"$$$$", "atmosphere":"Cozy", "name":"Ouzo Confuzo"},
{"location":"West Village","price":"$$$$", "atmosphere":"Cozy", "name":"Millennium Sandwich"},
{"location":"West Village","price":"$$$$", "atmosphere":"Cozy", "name":"Burnt Offerings"},
{"location":"West Village","price":"$$$$", "atmosphere":"Rooftop", "name":"Prawn Daddy"},
{"location":"West Village","price":"$$$$", "atmosphere":"Rooftop", "name":"Flame Thrower Grill"},
{"location":"West Village","price":"$$$$", "atmosphere":"Rooftop", "name":"Leather and Chrome"},
{"location":"West Village","price":"$$$$", "atmosphere":"Brunching", "name":"Oulu Rocinante"},
{"location":"West Village","price":"$$$$", "atmosphere":"Brunching", "name":"Psychic Pizza"},
{"location":"West Village","price":"$$$$", "atmosphere":"Brunching", "name":"Bitter Plaid"},
{"location":"East Village","price":"$", "atmosphere":"Romantic", "name":"Yogurt Transformation"},
{"location":"East Village","price":"$", "atmosphere":"Romantic", "name":"Janga Java"},
{"location":"East Village","price":"$", "atmosphere":"Romantic", "name":"Terrago"},
{"location":"East Village","price":"$", "atmosphere":"Trendy", "name":"Goat and Guru"},
{"location":"East Village","price":"$", "atmosphere":"Trendy", "name":"Brewed Attitude"},
{"location":"East Village","price":"$", "atmosphere":"Trendy", "name":"Linger Foods"},
{"location":"East Village","price":"$", "atmosphere":"Classy", "name":"Soprano"},
{"location":"East Village","price":"$", "atmosphere":"Classy", "name":"ButterFish"},
{"location":"East Village","price":"$", "atmosphere":"Classy", "name":"Exploded Shank"},
{"location":"East Village","price":"$", "atmosphere":"Cozy", "name":"BBQ Force"},
{"location":"East Village","price":"$", "atmosphere":"Cozy", "name":"Aglaya"},
{"location":"East Village","price":"$", "atmosphere":"Cozy", "name":"Caruso"},
{"location":"East Village","price":"$", "atmosphere":"Rooftop", "name":"Freakin' Planet"},
{"location":"East Village","price":"$", "atmosphere":"Rooftop", "name":"Chap and Spur"},
{"location":"East Village","price":"$", "atmosphere":"Rooftop", "name":"Dimple's"},
{"location":"East Village","price":"$", "atmosphere":"Brunching", "name":"Soft Shark"},
{"location":"East Village","price":"$", "atmosphere":"Brunching", "name":"Churros Welcome"},
{"location":"East Village","price":"$", "atmosphere":"Brunching", "name":"Antimatter"},
{"location":"East Village","price":"$$", "atmosphere":"Romantic", "name":"Taco Logic"},
{"location":"East Village","price":"$$", "atmosphere":"Romantic", "name":"The Bagel Barn"},
{"location":"East Village","price":"$$", "atmosphere":"Romantic", "name":"Quizmu"},
{"location":"East Village","price":"$$", "atmosphere":"Trendy", "name":"Wasabi Junction"},
{"location":"East Village","price":"$$", "atmosphere":"Trendy", "name":"The Royal Tease"},
{"location":"East Village","price":"$$", "atmosphere":"Trendy", "name":"Leaf and Stalk"},
{"location":"East Village","price":"$$", "atmosphere":"Classy", "name":"Millennarita"},
{"location":"East Village","price":"$$", "atmosphere":"Classy", "name":"Trophyplex"},
{"location":"East Village","price":"$$", "atmosphere":"Classy", "name":"Yuppie Slum"},
{"location":"East Village","price":"$$", "atmosphere":"Cozy", "name":"Epicurious George"},
{"location":"East Village","price":"$$", "atmosphere":"Cozy", "name":"La Concuna"},
{"location":"East Village","price":"$$", "atmosphere":"Cozy", "name":"Comfidant"},
{"location":"East Village","price":"$$", "atmosphere":"Rooftop", "name":"Tango Latté"},
{"location":"East Village","price":"$$", "atmosphere":"Rooftop", "name":"Steak And Shake"},
{"location":"East Village","price":"$$", "atmosphere":"Rooftop", "name":"Ear Roast"},
{"location":"East Village","price":"$$", "atmosphere":"Brunching", "name":"The Wedge"},
{"location":"East Village","price":"$$", "atmosphere":"Brunching", "name":"Juice Jones"},
{"location":"East Village","price":"$$", "atmosphere":"Brunching", "name":"Food Dump"},
{"location":"East Village","price":"$$$", "atmosphere":"Romantic", "name":"Campers"},
{"location":"East Village","price":"$$$", "atmosphere":"Romantic", "name":"Roosterville"},
{"location":"East Village","price":"$$$", "atmosphere":"Romantic", "name":"Funky Chicken Soup"},
{"location":"East Village","price":"$$$", "atmosphere":"Trendy", "name":"Sasskatchy!"},
{"location":"East Village","price":"$$$", "atmosphere":"Trendy", "name":"The Catfish Cathouse"},
{"location":"East Village","price":"$$$", "atmosphere":"Trendy", "name":"Corn Dog Social"},
{"location":"East Village","price":"$$$", "atmosphere":"Classy", "name":"Dandelar"},
{"location":"East Village","price":"$$$", "atmosphere":"Classy", "name":"The Spinach Armada"},
{"location":"East Village","price":"$$$", "atmosphere":"Classy", "name":"Zillaberry"},
{"location":"East Village","price":"$$$", "atmosphere":"Cozy", "name":"Chez Kicks"},
{"location":"East Village","price":"$$$", "atmosphere":"Cozy", "name":"Juggler's Jig"},
{"location":"East Village","price":"$$$", "atmosphere":"Cozy", "name":"Soul Depot"},
{"location":"East Village","price":"$$$", "atmosphere":"Rooftop", "name":"Multiple Cake"},
{"location":"East Village","price":"$$$", "atmosphere":"Rooftop", "name":"Kiss a Donut"},
{"location":"East Village","price":"$$$", "atmosphere":"Rooftop", "name":"Chew"},
{"location":"East Village","price":"$$$", "atmosphere":"Brunching", "name":"Attila the Honey Bee"},
{"location":"East Village","price":"$$$", "atmosphere":"Brunching", "name":"Counter Coutier"},
{"location":"East Village","price":"$$$", "atmosphere":"Brunching", "name":"Chaucer's Choice"},
{"location":"East Village","price":"$$$$", "atmosphere":"Romantic", "name":"The Orb"},
{"location":"East Village","price":"$$$$", "atmosphere":"Romantic", "name":"Glassinni"},
{"location":"East Village","price":"$$$$", "atmosphere":"Romantic", "name":"Howzit Go Inn"},
{"location":"East Village","price":"$$$$", "atmosphere":"Trendy", "name":"Friendly Fire"},
{"location":"East Village","price":"$$$$", "atmosphere":"Trendy", "name":"Tuna World"},
{"location":"East Village","price":"$$$$", "atmosphere":"Trendy", "name":"Rabbit Lounge"},
{"location":"East Village","price":"$$$$", "atmosphere":"Classy", "name":"Mauve Lava"},
{"location":"East Village","price":"$$$$", "atmosphere":"Classy", "name":"The Hoof and Snout"},
{"location":"East Village","price":"$$$$", "atmosphere":"Classy", "name":"Okratecture"},
{"location":"East Village","price":"$$$$", "atmosphere":"Cozy", "name":"Xth"},
{"location":"East Village","price":"$$$$", "atmosphere":"Cozy", "name":"Grits and Greetings"},
{"location":"East Village","price":"$$$$", "atmosphere":"Cozy", "name":"Food Prompt"},
{"location":"East Village","price":"$$$$", "atmosphere":"Rooftop", "name":"Road Rage Truck Stop"},
{"location":"East Village","price":"$$$$", "atmosphere":"Rooftop", "name":"Waffle Stomper"},
{"location":"East Village","price":"$$$$", "atmosphere":"Rooftop", "name":"Plumb Bum"},
{"location":"East Village","price":"$$$$", "atmosphere":"Brunching", "name":"Snail, Slug and Roach"},
{"location":"East Village","price":"$$$$", "atmosphere":"Brunching", "name":"Hat &amp; Goiter"},
{"location":"East Village","price":"$$$$", "atmosphere":"Brunching", "name":"Father Chutney"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Romantic", "name":"Pan Ash"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Romantic", "name":"The Lollytart"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Romantic", "name":"Neon"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Trendy", "name":"Flying Chaucer"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Trendy", "name":"bEarth"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Trendy", "name":"The Dining Car"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Classy", "name":"The Columner Pad"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Classy", "name":"Read and Feed"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Classy", "name":"Taco Forest"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Cozy", "name":"Elita"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Cozy", "name":"Hashed Browns and New Grounds"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Cozy", "name":"Netur"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Rooftop", "name":"Earthpure"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Rooftop", "name":"Spillway Tavern"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Rooftop", "name":"Coup de Veal"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Brunching", "name":"Above Bored"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Brunching", "name":"Humburger"},
{"location":"Greenwich Village","price":"$", "atmosphere":"Brunching", "name":"Cafe Inc."},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Romantic", "name":"Digging my Truffles"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Romantic", "name":"The Crumbery"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Romantic", "name":"Faster Faster Chicken Soup"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Trendy", "name":"Phlesh"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Trendy", "name":"Beef Burden"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Trendy", "name":"Cash Cow"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Classy", "name":"Guru Too"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Classy", "name":"Grits and Grace"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Classy", "name":"Aura Imploring Alice"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Cozy", "name":"Shellac and Hammock"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Cozy", "name":"Hambone Martian"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Cozy", "name":"Gelatosphere"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Rooftop", "name":"Wren"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Rooftop", "name":"Trollery"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Rooftop", "name":"Soul Massage"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Brunching", "name":"Lolita Proud"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Brunching", "name":"Performunch"},
{"location":"Greenwich Village","price":"$$", "atmosphere":"Brunching", "name":"Epstein's Bar and Grill"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Romantic", "name":"Naked Lunch"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Romantic", "name":"Fat Boy"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Romantic", "name":"Corn Husk Cafe"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Trendy", "name":"Coffee Science"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Trendy", "name":"FoodBuggy"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Trendy", "name":"Club Guru"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Classy", "name":"The Joy of Prawns"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Classy", "name":"Lectra"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Classy", "name":"Shakedown"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Cozy", "name":"Imperial Fire"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Cozy", "name":"Clarko"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Cozy", "name":"Kiwi Sea"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Rooftop", "name":"Interknack"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Rooftop", "name":"Django"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Rooftop", "name":"HighTee"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Brunching", "name":"Augrés"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Brunching", "name":"Clutch"},
{"location":"Greenwich Village","price":"$$$", "atmosphere":"Brunching", "name":"Balkan Beef"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Romantic", "name":"Jurassic Pork"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Romantic", "name":"Mr. Demeanor's"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Romantic", "name":"The Bison Wipe"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Trendy", "name":"Bela Bite"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Trendy", "name":"Coffee Farm"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Trendy", "name":"Cafe Lunch"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Classy", "name":"Potato Constant"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Classy", "name":"Of Corsica"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Classy", "name":"Facade"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Cozy", "name":"Flameboyant Grill"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Cozy", "name":"Octopus Garden"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Cozy", "name":"Tonque"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Rooftop", "name":"Dervish"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Rooftop", "name":"Memnonia"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Rooftop", "name":"Nada"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Brunching", "name":"Coffee King"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Brunching", "name":"Achilles"},
{"location":"Greenwich Village","price":"$$$$", "atmosphere":"Brunching", "name":"One For the Road Hog"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Romantic", "name":"Flying Monk"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Romantic", "name":"Rockyard"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Romantic", "name":"Symbiotica"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Trendy", "name":"Mister"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Trendy", "name":"Donut Babe"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Trendy", "name":"Roadkill Penguin"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Classy", "name":"The Crustacean"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Classy", "name":"Zoo Lulu"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Classy", "name":"Illustrioso"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Cozy", "name":"Skinny's Drive Inn"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Cozy", "name":"Monisphere"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Cozy", "name":"Curmudgeon Cafe"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Rooftop", "name":"Tickle's"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Rooftop", "name":"The Raspy Magpie"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Rooftop", "name":"Prawnto-Go"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Brunching", "name":"Cheese Picnic"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Brunching", "name":"Guru Planet"},
{"location":"Gramercy/FlatIron","price":"$", "atmosphere":"Brunching", "name":"Nylon Prawn"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Romantic", "name":"Giotto Gelato"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Romantic", "name":"Popcorn Born"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Romantic", "name":"Spanish Harem"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Trendy", "name":"Soup-In"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Trendy", "name":"Diseasia"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Trendy", "name":"Web Wash"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Classy", "name":"Mauve Rocket"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Classy", "name":"Port O' Prawn"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Classy", "name":"BigWay"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Cozy", "name":"Megall"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Cozy", "name":"Salud!"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Cozy", "name":"Iron Bone"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Rooftop", "name":"VegiGate"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Rooftop", "name":"On the Bar B"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Rooftop", "name":"Mantiquilla"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Brunching", "name":"Leucrid"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Brunching", "name":"The Prawn Shop"},
{"location":"Gramercy/FlatIron","price":"$$", "atmosphere":"Brunching", "name":"Aquazure"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Romantic", "name":"Hot Trotsky"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Romantic", "name":"Vanity Fare"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Romantic", "name":"Zutros"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Trendy", "name":"Drive Vibe"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Trendy", "name":"Boil Head"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Trendy", "name":"Prawn Panic"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Classy", "name":"Menthol"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Classy", "name":"Bing Bang's"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Classy", "name":"Soul Kitsch"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Cozy", "name":"Grounds Zero"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Cozy", "name":"Maple Thor"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Cozy", "name":"Zentia"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Rooftop", "name":"Cafe Stuff't"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Rooftop", "name":"eMantis"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Rooftop", "name":"Thirst ‘n Howl"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Brunching", "name":"Overchurros"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Brunching", "name":"Rib Rage"},
{"location":"Gramercy/FlatIron","price":"$$$", "atmosphere":"Brunching", "name":"The Potato Constant"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Romantic", "name":"Cafe Brood"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Romantic", "name":"Souther Proper"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Romantic", "name":"Partyclub"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Trendy", "name":"The Bid and the Ask"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Trendy", "name":"Phobia"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Trendy", "name":"The One-Up"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Classy", "name":"Bar Flight"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Classy", "name":"Cafe Plutarch"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Classy", "name":"Jaws"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Cozy", "name":"Taxi Dance"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Cozy", "name":"Little Mussolini"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Cozy", "name":"Precious Potato"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Rooftop", "name":"Taste Makes Waist"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Rooftop", "name":"Bengal Bagel"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Rooftop", "name":"Tuna Bar"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Brunching", "name":"Cup and Chaucer"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Brunching", "name":"Kundalini's"},
{"location":"Gramercy/FlatIron","price":"$$$$", "atmosphere":"Brunching", "name":"Nosh Online"},
{"location":"Chelsea","price":"$", "atmosphere":"Romantic", "name":"GeekChicken"},
{"location":"Chelsea","price":"$", "atmosphere":"Romantic", "name":"Jupitor Place"},
{"location":"Chelsea","price":"$", "atmosphere":"Romantic", "name":"Tomatofish"},
{"location":"Chelsea","price":"$", "atmosphere":"Trendy", "name":"Thalia"},
{"location":"Chelsea","price":"$", "atmosphere":"Trendy", "name":"Butter Butt"},
{"location":"Chelsea","price":"$", "atmosphere":"Trendy", "name":"Endozilla"},
{"location":"Chelsea","price":"$", "atmosphere":"Classy", "name":"Sevére"},
{"location":"Chelsea","price":"$", "atmosphere":"Classy", "name":"Slush Fund"},
{"location":"Chelsea","price":"$", "atmosphere":"Classy", "name":"Que"},
{"location":"Chelsea","price":"$", "atmosphere":"Cozy", "name":"Tunnel of Coffee"},
{"location":"Chelsea","price":"$", "atmosphere":"Cozy", "name":"Taste Tease"},
{"location":"Chelsea","price":"$", "atmosphere":"Cozy", "name":"Armadillo Plates"},
{"location":"Chelsea","price":"$", "atmosphere":"Rooftop", "name":"Tiki Taco"},
{"location":"Chelsea","price":"$", "atmosphere":"Rooftop", "name":"Sobriety Checkpoint"},
{"location":"Chelsea","price":"$", "atmosphere":"Rooftop", "name":"Phat Transient"},
{"location":"Chelsea","price":"$", "atmosphere":"Brunching", "name":"The Tumbler and the Twist"},
{"location":"Chelsea","price":"$", "atmosphere":"Brunching", "name":"Water Back"},
{"location":"Chelsea","price":"$", "atmosphere":"Brunching", "name":"Condimantra"},
{"location":"Chelsea","price":"$$", "atmosphere":"Romantic", "name":"Taco Boil"},
{"location":"Chelsea","price":"$$", "atmosphere":"Romantic", "name":"Tort Resort"},
{"location":"Chelsea","price":"$$", "atmosphere":"Romantic", "name":"The Prawn and the Poi"},
{"location":"Chelsea","price":"$$", "atmosphere":"Trendy", "name":"Caffeine Wall"},
{"location":"Chelsea","price":"$$", "atmosphere":"Trendy", "name":"Ndoor"},
{"location":"Chelsea","price":"$$", "atmosphere":"Trendy", "name":"Smoochy Goochy Bar"},
{"location":"Chelsea","price":"$$", "atmosphere":"Classy", "name":"Bagel Palace"},
{"location":"Chelsea","price":"$$", "atmosphere":"Classy", "name":"Shame Bait"},
{"location":"Chelsea","price":"$$", "atmosphere":"Classy", "name":"Molten Tacos"},
{"location":"Chelsea","price":"$$", "atmosphere":"Cozy", "name":"Southern Mash"},
{"location":"Chelsea","price":"$$", "atmosphere":"Cozy", "name":"Call it Green"},
{"location":"Chelsea","price":"$$", "atmosphere":"Cozy", "name":"Humvegan"},
{"location":"Chelsea","price":"$$", "atmosphere":"Rooftop", "name":"Revenue"},
{"location":"Chelsea","price":"$$", "atmosphere":"Rooftop", "name":"Runt and Rove"},
{"location":"Chelsea","price":"$$", "atmosphere":"Rooftop", "name":"Koffee Kat"},
{"location":"Chelsea","price":"$$", "atmosphere":"Brunching", "name":"Liquid Kitty"},
{"location":"Chelsea","price":"$$", "atmosphere":"Brunching", "name":"Oulu"},
{"location":"Chelsea","price":"$$", "atmosphere":"Brunching", "name":"Liquid Radiant"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Romantic", "name":"Easy Beef"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Romantic", "name":"On Golden Prawn"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Romantic", "name":"Time For Coffee"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Trendy", "name":"The Lunch"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Trendy", "name":"Zilla"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Trendy", "name":"Rabid Rabbit"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Classy", "name":"Turnling"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Classy", "name":"Mammy's Yammys"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Classy", "name":"The Glassy Eye"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Cozy", "name":"Cafe Fin"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Cozy", "name":"Elpro"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Cozy", "name":"Acapulco Gold"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Rooftop", "name":"Foodbowl"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Rooftop", "name":"Kick the Beckett"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Rooftop", "name":"Limozen"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Brunching", "name":"The Dollop"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Brunching", "name":"Ensanada"},
{"location":"Chelsea","price":"$$$", "atmosphere":"Brunching", "name":"Celeste"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Romantic", "name":"Five O'clock Shadow"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Romantic", "name":"Grill to Chill"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Romantic", "name":"Nasdaquiri"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Trendy", "name":"Flange"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Trendy", "name":"Voodude Ranch"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Trendy", "name":"The Spring"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Classy", "name":"Geos"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Classy", "name":"AstroCoffee"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Classy", "name":"Fiber"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Cozy", "name":"Surf and Scarf"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Cozy", "name":"Jack."},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Cozy", "name":"Prawn Phreak"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Rooftop", "name":"Oscillation"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Rooftop", "name":"Peek-A-Boo Pork"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Rooftop", "name":"Hindenburger"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Brunching", "name":"Tequila Mockingbird"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Brunching", "name":"The Bind"},
{"location":"Chelsea","price":"$$$$", "atmosphere":"Brunching", "name":"Godzilla Pizza"},
];